spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/selvasingh/spring-cloud-gateway-config
        native:
          search-locations: classpath:.
  profiles:
    active: native
